version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - "./srs-pg/:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_PASSWORD=srs
      - POSTGRES_USER=srs
      - POSTGRES_DB=srs