begin;

CREATE TABLE IF NOT EXISTS symbolset
(
    symbolset VARCHAR NOT NULL,
    symbolsetname VARCHAR
);
INSERT INTO SYMBOLSET (symbolset,symbolsetname) VALUES ('10','LAND UNIT'),
('11','LAND CIVILIAN UNIT/ORGANIZATION'),
('15','LAND EQUIPMENT'),
('20','LAND INSTALLATIONS'),
('25','CONTROL MEASURE'),
('30','SEA SURFACE'),
('35','SEA SUBSURFACE'),
('36','MINE WARFARE'),
('40','ACTIVITY/EVENT'),
('50','SIGNALS INTELLIGENCE – SPACE'),
('51','SIGNALS INTELLIGENCE – AIR'),
('52','SIGNALS INTELLIGENCE – LAND'),
('53','SIGNALS INTELLIGENCE – SURFACE'),
('54','SIGNALS INTELLIGENCE – SUBSURFACE'),
('60','CYBERSPACE'),
('01','AIR'),
('02','AIR MISSILE'),
('05','SPACE'),
('06','SPACE MISSILE');
commit;
